### ISSUE TITLE
Broken under Gnome Shell 3.36

### ISSUE THREAD

**Issue by ghost** [Maestroschan/appfolders-manager-gnome-extension#104]
I'm currently running Ubuntu 20.04 and Gnome Shell 3.36
Up until recent Gnome Shell updates the extension was working flawlessly, however now when the Applications window is opened, it opens with no icons, and then temporarily freezes the desktop before crashing and restarting it.
Tested by enabling and disabling all gnome extensions under a clean build, and the fault only appears when this extension is enabled.
Internet searches have indicated this is now a known fault with this extension and advises that it is disabled.
A bug fix (unfortunately out of my capabilities) would be good as this was a valued extension.

I've seen comments that this is now has native support in the Gnome Shell, however this does not appear to be the case under Ubuntu 20.04 - either that or I am missing something.

And just to prove me wrong, upon uninstalling the extension, the ability to drag and dop icons on the Applications window, etc., started to work.

**Comment by maoschanz** [comment]
>either that or I am missing something

You were missing that my extension doesn't support 3.36 because it's conflicting with the new default behaviour
