### ISSUE TITLE
"Add" menu button when creating an appFolder

### ISSUE THREAD

**Issue by alex285** [Maestroschan/appfolders-manager-gnome-extension#14]
when we create a new folder, there is a "Cancel" button, and we should press Enter for creating it

![games-bug](https://user-images.githubusercontent.com/11244308/26918838-48cdbe0a-4c3c-11e7-83af-445c4d65dc50.png)

can be an "Add" button on the right of "Cancel" so we can do the same with mouse of touch? that will also expand the input size which currently is very small!

moreover it should check for availability, for example not having two appFolders with same name, or have invalid characters, but only alphanumerics and spaces

**Comment by maoschanz** [comment]
It looks like there is no invalid character : i had tested with exotic japanese characters, apostrophes, quotation marks, backslashs, both, these all worked.

The extension should already check if an appfolder already exists with the same name, however there is no visual indication of it yet, i will try to had an error message (and your other ideas) in the next update.

**Comment by maoschanz** [comment]
Concerning width, it looks like it is a ![](http://i.imgur.com/UWdcTPL.png) for now :')

**Comment by maoschanz** [comment]
I have tried something. I'm not sure of the error message's conjugation but it looks nice.

**Comment by alex285** [comment]
nice! thank you!
