### ISSUE TITLE
an option do disable appFolders menu from Panels/Docks

### ISSUE THREAD

**Issue by alex285** [Maestroschan/appfolders-manager-gnome-extension#15]
behavior:
appFolder menu can be open both from Shell appOverview and from Shell Dock. 
same behavior happens on Dash to Panel, when the appFolder menu is accessible from panel's appIcons. that doesn't make much of sense, plus it loads the menu

video that demos the issue (sorry about that kind of video!)
https://www.youtube.com/watch?v=S6PA2fIw-Ak

if not disabled by default, could be an option that would disable appFolder for Docks/Panels please?

**Comment by maoschanz** [comment]
Done, but it's not an option

**Comment by alex285** [comment]
just tried it! thank you!
