### ISSUE TITLE
Hide apps on menu

### ISSUE THREAD

**Issue by Cookie74** [Maestroschan/appfolders-manager-gnome-extension#19]
I want request a feature to hide apps on menu , just appear on the search in the search bar
![image](https://user-images.githubusercontent.com/30097589/28334390-5cc285e4-6bd1-11e7-85e8-bb20de315f25.png)

**Comment by maoschanz** [comment]
the idea is interesting, but there is a problem about "how to unhide things", i will try something about it in september

**Comment by maoschanz** [comment]
I think it requires a dedicated extension
