### ISSUE TITLE
Various things to do

### ISSUE THREAD

**Issue by maoschanz** [Maestroschan/appfolders-manager-gnome-extension#2]
Version 2 of the extension : 
_italic = done_
**bold = work in progress**

Done things are not available on github immediatly.

## Differences between v1 and v2 (May 22th to June 5th)
* _reload the view after each operation (bug if the number of pages changes)_
* _delete ALL appfolder-related things in gsettings when an appfolder is deleted (option)_
* _do a less ugly thing concerning the "new appfolder" submenu (just a menu item opening a popup with a text entry is better)_
* _show the ability to "delete from" only if the item should be concerned_
* _not allow multiple occurences of a folder_
* _not allow multiple occurences of an item in a folder_
* _display folders' actual names instead of their id_
* _better organization of the code_
* _merging features of my other extension about the number of column into this extension (+ add appfolders support for the concept)_ (initialization issue ? it doesn't work only the first time ?)
* _an icon for extensions.gnome.org_
* _translations ( .pot file with v2 + v3 together)_
--------------------
* _allow creation of new folder within a folder (by calling "popdown" before creating the entry)_
* _folder icon should change when adding/removing (i guess there is a problem about objects i don't destroy, but i can't destroy them so f*ck it at least it works)_
* _appfolders' content is not shown with the good number of columns despite the setting which works (initialization issue ?)_ my solution is ugly as hell but it works, except when creating a new appfolder ?
* _Shell Toolkit doesn't like when the item my menu comes from is deleted_
* Main.overview.viewSelector.appDisplay._views[1].view._grid._grid.destroy_all_children() est MERDIQUE DE SA RACE LA PUTE _du coup on va faire remove_all_children hein._ Ceci dit notons que la fonction peut être appelée depuis looking glass avec succès. À l'avenir, il faudra surveiller l'évolution de ce bug en fonction des versions de GS. Pourquoi pas si j'ai que ça à foutre, patcher le problème.
--------------------
## Tests (version 2 ; June 2nd)
**With 3.22 (Debian)** ; Warnings in logs : 
* `(gnome-shell:4629): St-CRITICAL **: st_widget_get_theme_node called on the widget [0x556678e92f30 StButton.app-well-app app-folder ("Accessoires")] which is not in the stage.` (add an item from Accessoires to another folder)
* `(gnome-shell:4629): St-CRITICAL **: st_widget_get_theme_node called on the widget [0x55667d4540d0 StBin.popup-menu-boxpointer popup-menu app-well-menu] which is not in the stage.` (remove an item from a folder)
* 
```
(gnome-shell:4629): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
(gnome-shell:4629): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
(gnome-shell:4629): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
(gnome-shell:4629): Clutter-CRITICAL **: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
(gnome-shell:4629): Clutter-CRITICAL **: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
```
(deleting a folder from outside itself)
* 
```
(gnome-shell:4629): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
(gnome-shell:4629): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
(gnome-shell:4629): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
(gnome-shell:4629): Clutter-CRITICAL **: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
(gnome-shell:4629): Clutter-CRITICAL **: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
(gnome-shell:4629): Clutter-CRITICAL **: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
```
(deleting a folder from inside itself)

### Checklist : 
for each action, if the number of pages changes or not, from the "allview", from the concerned folder, from another folder
* good display at initialization
* doesn't f*cking crash the whole shell
* scrolling after use
* no warning in logs

**Comment by maoschanz** [comment]
Version 2.2 (published)
* _The dialog bug_ (fixed)
* _wider dialog (add an "add" button)_
* _show an graphical error instead of a lazy log (when 2 folders have same nnames)_
* _The "incorrect pop" when delete from inside an appfolder is très chiant._

Version 2.3 : 
* _show menu items only in the app view_
* `(gnome-shell:3822): Clutter-CRITICAL **: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed` un par ouverture de dialog, mais ils s'accumulent mazette
* The dialog focus is sometimes broken
* "Complete deletion" works only if nickname and name correspond ?
* _oups i forgot to write a file mentionning all contributors_ now in the readme

---------

Version 3 : 
* **right click on an appfolder to delete (and rename) it instead of having a "Delete appfolder" submenu everywhere (delete it)** - rofl c'est trop honteux je commente en français :
  * ça a empiré le bug à l'initialisation (essayer un vieux timeout de ses morts pour tenter) ;
  * le code est HIDEUX ; quitte à me battre les burnes des signaux, autant les virer tous ?
  * _empêcher plusieurs menus en même temps_ ;
  * après c'est juste des connexions ;
  * faire un disable correct (et virer les "prototype" ?)
  * erreur quand on supprime un truc qu'on a renommé (pb de signal ?)
* add items to folders with dnd (do not delete the submenu)
* better organization of the code

**Comment by pkomur** [comment]
It would be great to organize appfolder by drag and drop of icons.

**Comment by maoschanz** [comment]
Yes, it's what i meant by "add items with dnd" for the version 3, but i first want to finish a clean version 2 with contextual menus (for now the version 2 as some bugs which i don't understand yet).

However, drag & drop can't replace the submenu (which is convenient to add things in folders using the research)
