### ISSUE TITLE
A few apps have no remove menu

### ISSUE THREAD

**Issue by ddnexus** [Maestroschan/appfolders-manager-gnome-extension#20]
E.g. Utilities > Archive manager, Utilities > Logs, Utilities > Tilix

**Comment by maoschanz** [comment]
What is the distro ?

**Comment by ddnexus** [comment]
Ubuntu GNOME latest

**Comment by maoschanz** [comment]
Could you give the results of
`gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Utilities/ apps`
and
`gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Utilities/ categories`
please ?

**Comment by ddnexus** [comment]
> gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Utilities/ apps
['org.gnome.baobab.desktop', 'deja-dup-preferences.desktop', 'eog.desktop', 'evince.desktop', 'org.gnome.FileRoller.desktop', 'gnome-calculator.desktop', 'gnome-dictionary.desktop', 'org.gnome.Characters.desktop', 'org.gnome.DiskUtility.desktop', 'org.gnome.font-viewer.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Screenshot.desktop', 'gnome-system-log.desktop', 'gnome-system-monitor.desktop', 'gnome-tweak-tool.desktop', 'gucharmap.desktop', 'seahorse.desktop', 'vinagre.desktop', 'yelp.desktop', 'ca.desrt.dconf-editor.desktop']
 
 > gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Utilities/ categories
['X-GNOME-Utilities']

**Comment by maoschanz** [comment]
ok thanks, i understand what the problem is.

I will begin to fix this right now but i don't know when it will be ready

Try to do 
`gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Utilities/ categories []`
for now, it should solve your issue.

**Comment by ddnexus** [comment]
> gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Utilities/ categories []
zsh: no matches found: []

Besides, opening the Utility folder key (or any other created folder) with dconf Editor gives No Schema Found.

**Comment by maoschanz** [comment]
Since you could "get" the key via gsettings, the path /org/gnome/desktop/app-folders/folders/Utilities/categories should exists in the dconf editor. I also have a "no schema found" indication when i'm at /org/gnome/desktop/app-folders/folders/Utilities/, but i still can edit the "categories" key and replace its value by [].

**Comment by maoschanz** [comment]
ok so, i did a new version (only on github for now): you can install it, then do a right-click on the folder, you'll have a "remove a category" submenu, where there is something like "X-GNOME-Utilities".
Tilix etc. can be removed by removing this whole category.
