### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Warmuser** [Maestroschan/appfolders-manager-gnome-extension#21]
Please, add  the possibility to Add the AppFolders to the favourites in Dash to panel/Dash to dock extensions.

**Comment by maoschanz** [comment]
This possibility doesn't exist in the "vanilla" dash, nor in Dash to dock, nor in Dash to panel.
The idea is good, but the part of the interface to tweak is very different, and it should be a standalone extension

**Comment by Warmuser** [comment]
Ok, anyway thank you for responding me! :)
