### ISSUE TITLE
Problems with the extension!

### ISSUE THREAD

**Issue by Warmuser** [Maestroschan/appfolders-manager-gnome-extension#26]
Hello Maestrochan, If I enable the extension I get these problems:

1) If I open any appfolder the content inside become  invisibile: http://imgbox.com/Bla4ZnG5
2) And once opened some folder, it remains opened, it doesn't close also If I disable the extension.
3) The application menu doesn't scroll well when the extension is active.

My specs:

Desktop Environment: GNOME v3.24.2
Distro: Manjaro v17.0.2
Kernel Linux v4.9.40-1-MANJARO
Shell: bash v4.4.12
I run the OS on VMWare Workstation 12 Player
My machine is based on a i5 configuration.

**Comment by maoschanz** [comment]
I'm aware of scrolling problems, but it's not very serious.

The other bugs are more strange...

What are applications in this folder ?
And what is the theme ?

Can you disable the extension, restart GNOME Shell (in the Alt+F2 dialog, type "r"), and then try to open/close an appfolder ?

**Comment by Warmuser** [comment]
@Maestroschan I tried with any application, I think it is not a problem of incompatibility. Inside the folder, I have the Web Browsers: firefox, chrome and opera. My theme is the Adapta. I also tried to restart the shell but nothing has changed. 

I also can't also delete the appfolder, the right click doesn't open the mouse menu.

**Comment by Warmuser** [comment]
Anyway I disabled all my installed extension and I decided to enable one at time. And I encountered all the described conflicts caused when the "Magnifer Improvements" is enabled. 

I also encountered a little issue when I enabled the Darker Overview extension http://imgbox.com/NS25QoTa.  Can If you can fix it?

PS: I also want to give you one new suggestion:

1) Can you can add the possibility to drag the folders to change their position on the Application menu grid?

Let me know If it is possible, anyway thanks for the support! :)

**Comment by maoschanz** [comment]
The right click on folders is very buggy (maybe the buggiest thing in the extension), it doesn't appears each time, especially if you just did an other operation with the extension. Just close and open the overview again, it should appear.

With dconf-editor, you can go to /org/gnome/desktop/app-folders/folders/ and see all folders and their contents, can you do a screenshot of what's in the Network folder ?

----

I don't know the Darker Overview extension, so i don't understand what is wrong in your screenshot, however notice that I didn't invent the concept of appfolder, it is a default feature of GNOME Shell: if "Darker Overview" doesn't support appfolders, it's a bug you should report to its developer

**Comment by Warmuser** [comment]
Nope, I  did a mistake.. I disabled again all the extension and I repeated the procedure. The bug is caused by user themes extension. Anyway I tried also to switch to another theme and the bug has become much visible.. I can see the darker background also in each unopened folder.

I will report these problem to the owner of user themes. :)

PS: I made a video for the dconf-editor: https://www.youtube.com/watch?v=USeMJIYXUv4

**Comment by Warmuser** [comment]
I also made a test video where I disable and enable the extensions, I want to show you more..

Demostration: https://www.youtube.com/watch?v=f_ZFu-6-O_w

**Comment by maoschanz** [comment]
Ok, the content of dconf-editor seems correct, it just looks like the "Magnifier Improvements" extension breaks appfolders displaying in general (and not only with my extension).
I tested it, and the scrolling issue it creates is seriously troublesome, it wasn't what i expected, the code looks like the developer doesn't even know appfolders exist.

As i said, i didn't invent appfolders themselves, it's a native thing: if Magnifier Improvements doesn't support a GNOME Shell default feature, it's a problem for the Magnifier Improvements developer.

Concerning themes, appfolders having a different background color is a normal behavior, sometimes it's more grey, sometimes more dark,... i don't really know how theming works (the only "esthetic" aspect my extension can manage is the number of columns)

>Can you can add the possibility to drag the folders to change their position on the Application menu grid?

That is very complex, but you gave me an other idea: i will try to add a setting which will display appfolders first and other applications below

**Comment by Warmuser** [comment]
Ok, good to know. Anyway thanks for the support! :)
