### ISSUE TITLE
Various things to do

### ISSUE THREAD

**Issue by maoschanz** [Maestroschan/appfolders-manager-gnome-extension#27]
# Drag and drop for add/remove
With the current implementation of appDisplay.js, this seems impossible to do "naturally".

- Special overlay actors have to be created just for dropping apps ?
- How tf should the user do for adding an item from page 1 to a folder for page 2 ?
- Should these overlay actors not be atop of their respective foldericon ?

# Drag and drop for creating appfolders

- An overlay actor with a +, which triggers the dialog

# An option for putting appfolders first in the list

It looks impossible.

**Comment by gmagic** [comment]
It would be great to reach osx launcher functionality.

Like your ext. Thanks!
