### ISSUE TITLE
On Gnome 3.28 the launchers wont stay inside a group

### ISSUE THREAD

**Issue by reya276** [Maestroschan/appfolders-manager-gnome-extension#42]
On Gnome 3.28 the launchers wont stay inside a group after starting a new session. Meaning that is I install an app such as WPS office those icons won't stay inside the Office group.

**Comment by maoschanz** [comment]
could you please precise:

- what version you use (the one from extensions.gnome.org or the one from here)
- how you add apps (by using the "Office" category or by adding launchers one by one)
- the result of:

```
gsettings get org.gnome.desktop.app-folders folder-children
gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/Office/ categories
gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/Office/ apps
gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/Office/ excluded-apps
```

**Comment by reya276** [comment]
> could you please precise:
> 
> * what version you use (the one from extensions.gnome.org or the one from here)
> * how you add apps (by using the "Office" category or by adding launchers one by one)
> * the result of:
> 
> ```
> gsettings get org.gnome.desktop.app-folders folder-children
['Pop-Office', 'Pop-System', 'Pop-Utility', 'Development', 'Design', 'Google']

> gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/Office/ categories
@as []

> gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/Office/ apps
@as []

> gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/Office/ excluded-apps
@as []
> ```

Oh I added them one at a time and I believe I added the extension form the Gnome site.

**Comment by maoschanz** [comment]
Ah, Pop_OS...

Then, the 3 last ones but with Pop-Office instead of Office

**Comment by reya276** [comment]
> Ah, Pop_OS...
> 
> Then, the 3 last ones but with Pop-Office instead of Office

How do I set the option?

**Comment by maoschanz** [comment]
what options ? i'm just asking the 3 last commands again but with the correct name, which is Pop-Office (not Office, the answer to the commands were empty because there is no folder with the id "Office")
