### ISSUE TITLE
Error when creating app folder

### ISSUE THREAD

**Issue by MikeyG** [Maestroschan/appfolders-manager-gnome-extension#43]
I am not sure what happened, but after updating my Gentoo system a number of applications appeared outside of their folders. The apps were still in the assigned folders too. I tried creating a test folder (newapp folder) and Gnome sometime resets and I get this error:

`gnome-shell[3450]: JS ERROR: TypeError: appIcon is undefined
                                              AllView<._refilterApps/</<@resource:///org/gnome/shell/ui/appDisplay.js:507:17
                                              AllView<._refilterApps/<@resource:///org/gnome/shell/ui/appDisplay.js:505:13
                                              AllView<._refilterApps@resource:///org/gnome/shell/ui/appDisplay.js:503:9
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                              AllView<._loadApps@resource:///org/gnome/shell/ui/appDisplay.js:553:9
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                              BaseAppView<._redisplay@resource:///org/gnome/shell/ui/appDisplay.js:154:9
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                              reload@/home/mgreene/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:612:2
                                              addToFolder@/home/mgreene/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:605:2
                                              AppfolderDialog<._create@/home/mgreene/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:255:3
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                              AppfolderDialog<._addfolder@/home/mgreene/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:212:3
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                              AppfolderDialog<._function@/home/mgreene/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:171:5
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22

gnome-shell[3450]: destroying
`

**Comment by maoschanz** [comment]
>extension.js:612

I know i should have updated the version on extensions.gnome.org but i didn't, so you're using something so old i can't know what the bug is: `extension.js` doesn't have so many lines nowadays

**Comment by MikeyG** [comment]
Okay, I'll download the current and check for the issue.

**Comment by maoschanz** [comment]
i didn't upload it because it's not very stable (and not compatible with every version, and i've no idea what Gentoo uses)

**Comment by MikeyG** [comment]
I am using Gnome 3.26.2.  So here is an example, I tried to add an app to a folder using the master code:

`Nov 14 17:30:32 littleturd gnome-shell[3450]: JS ERROR: Exception in callback for signal: apps-changed: TypeError: appIcon is undefined
                                              AllView<._refilterApps/</<@resource:///org/gnome/shell/ui/appDisplay.js:507:17
                                              AllView<._refilterApps/<@resource:///org/gnome/shell/ui/appDisplay.js:505:13
                                              AllView<._refilterApps@resource:///org/gnome/shell/ui/appDisplay.js:503:9
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                              _emit@resource:///org/gnome/gjs/modules/signals.js:126:27
                                              FolderIcon<._redisplay@resource:///org/gnome/shell/ui/appDisplay.js:1368:9
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                              addToFolder@/home/mgreene/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:604:2
                                              injectionInAppsMenus/injections._redisplay</<@/home/mgreene/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:470:7
                                              _emit@resource:///org/gnome/gjs/modules/signals.js:126:27
                                              PopupBaseMenuItem<.activate@resource:///org/gnome/shell/ui/popupMenu.js:166:9
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                              PopupBaseMenuItem<._onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:127:9
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Nov 14 17:30:34 littleturd gnome-shell[3450]: JS ERROR: Exception in callback for signal: activate: TypeError: appIcon is undefined
                                              AllView<._refilterApps/</<@resource:///org/gnome/shell/ui/appDisplay.js:507:17
                                              AllView<._refilterApps/<@resource:///org/gnome/shell/ui/appDisplay.js:505:13
                                              AllView<._refilterApps@resource:///org/gnome/shell/ui/appDisplay.js:503:9
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                              AllView<._loadApps@resource:///org/gnome/shell/ui/appDisplay.js:553:9
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                              BaseAppView<._redisplay@resource:///org/gnome/shell/ui/appDisplay.js:154:9
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                              reload@/home/mgreene/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:612:2
                                              addToFolder@/home/mgreene/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:605:2
                                              injectionInAppsMenus/injections._redisplay</<@/home/mgreene/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:470:7
                                              _emit@resource:///org/gnome/gjs/modules/signals.js:126:27
                                              PopupBaseMenuItem<.activate@resource:///org/gnome/shell/ui/popupMenu.js:166:9
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                              PopupBaseMenuItem<._onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:127:9
                                              wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
`

**Comment by maoschanz** [comment]
>using the master code

This can't be the code from master, on master `extension.js` has only 380 lines and you still have a trace with 612:2  and 605:2

But whatever, it's not important because i read the code of gnome-shell 3.26.2 and i can guess what the error is. Open `dconf-editor` and go to `/org/gnome/desktop/app-folders/`

Here, edit values to delete all suspect things, both in folder-children (which is the ids of existing folders) and in `folders` (which contains details about the content of all folders)

**Comment by MikeyG** [comment]
Yes, this worked.  A folder named SystemTools had some type of issue and it caused it and all folders after to have issues. I deleted and setup again which fixed it. Thanks.
