### ISSUE TITLE
Official extensions badge

### ISSUE THREAD

**Issue by andyholmes** [Maestroschan/appfolders-manager-gnome-extension#44]
Hi, about a week ago I asked for "Get it on..." badge for extensions like Google Play has, so GNOME had their marketing designer Caroline Henriksen make an official badge for us. They asked if I'd contact a few extension developers to get the word out.

[<img src="https://raw.githubusercontent.com/andyholmes/gnome-shell-extensions-badge/master/get-it-on-ego.svg?sanitize=true" height="100">](https://extensions.gnome.org/extension/1217/appfolders-manager/)

There is a PNG and SVG available that you can host yourself, possibly link from the [GitLab issue](https://gitlab.gnome.org/Teams/Engagement/marketing-design/issues/3), or I have a [repository on Github](https://github.com/andyholmes/gnome-shell-extensions-badge) you can link from (see the raw markdown from this comment for using SVG on Github).

Or just feel free to close the issue if you're not interested! Thanks for your extension, this is one of first installs after dash-to-dock :)

**Comment by maoschanz** [comment]
Yes i saw it on reddit (and already added it [here](https://github.com/maoschanz/Places-and-files-direct-access/blob/master/README.md)) i will add it to my other extensions when i will have time to take care of them

**Comment by andyholmes** [comment]
Sounds good, I haven't actually done it myself 😛
