### ISSUE TITLE
Possibility to create  versioning release?

### ISSUE THREAD

**Issue by Ste74** [Maestroschan/appfolders-manager-gnome-extension#45]
Hi there,
i'm a part of Manjaro and maintainer of Gnome edition; i want include your work in the default ISO of Gnome. Not a big issue since i can use the git commit to do the versioning but to divide a stable release and development work i ask if is possible adopt a versioning number for your work.

Thank in advance

Stefano Capitani
Manjaro Core Team

**Comment by maoschanz** [comment]
Before adopting a versioning number, i should adopt a working code, because everything here has been a mess for months. I'll try to do something about it during this week

**Comment by Ste74** [comment]
Ok, thank you :+1:

**Comment by maoschanz** [comment]
The code works on my machine, i improved it on many aspects and drag-and-drop should now work without performance issues, but i don't know how it behaves on Manjaro, you may want to test it before.

**Comment by Ste74** [comment]
Yep, last development (git) version is in our unstable branch :+1:

**Comment by Ste74** [comment]
Sorry for delay.. now use the git tag to build .. thank you

**Comment by maoschanz** [comment]
wow i didn't even remember when was the last time i release something with a tag here, i should reinstall that and update it a bit
