### ISSUE TITLE
Not stable

### ISSUE THREAD

**Issue by tio-trom** [Maestroschan/appfolders-manager-gnome-extension#46]
In my experience with this extension it restarts the Gnome Shell multiple times when I am trying to move apps from one folder to another and I think it causes other issues too. I tried to test this by deactivating all extensions but it, and still saw issues. Anyone else experiencing this?

**Comment by maoschanz** [comment]
it's very likely, because it's not very well tested. What version of GNOME Shell are you using ? Also, is the extension from the master branch, or from the gnome website ?

**Comment by tio-trom** [comment]
gnome-shell  1:3.30.1-1

The version os from the gnome website. The extension is so useful that even with these bugs I cannot give up on it. It should be default in Gnome to be honest.

**Comment by maoschanz** [comment]
>when I am trying to move apps from one folder to another

Do you add the app to the 2nd folder and then remove from the first, or remove from the 1st and then add it the the 2nd ?

**Comment by tio-trom** [comment]
Add an app to a folder, then from that folder add it to another

**Comment by maoschanz** [comment]
i tried with the "master" version of the extension:

- doing that with the right-click menu "only" freezes GNOME Shell for around 3 seconds
- doing that with the drag-and-drop works fine

but no actual crash.

So maybe i fixed this issue unintentionally

**Comment by TROMsite** [comment]
By the "master" version you mean the one from gnome website?
Also, I had no clue there is a drag and drop. I cannot drag and drop....what am I doing wrong? :D

**Comment by tio-trom** [comment]
By the "master" version you mean the one from gnome website?
Also, I had no clue there is a drag and drop. I cannot drag and drop....what am I doing wrong? :D

**Comment by maoschanz** [comment]
no i mean the one from the "master" branch of this repo. The version from the gnome website is almost one year old and has no drag-and-drop

**Comment by tio-trom** [comment]
Ah ok. Do you plan to update the gnome website one? :)

**Comment by maoschanz** [comment]
Yes, when the version from the repo will be better

**Comment by tio-trom** [comment]
Awesome. Thank you!
