### ISSUE TITLE
allAppsGrid._grid is undefined

### ISSUE THREAD

**Issue by alex285** [Maestroschan/appfolders-manager-gnome-extension#47]
it's on GNOME 3.31.2 so you need a Rawhide to debug that
```
JS ERROR: Exception in callback for signal: drag-begin: TypeError: allAppsGrid._grid is undefined
ensureFolderOverlayActors@/home/alex/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/dragAndDrop.js:203:7
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
on_drag_begin@/home/alex/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/dragAndDrop.js:90:3
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
initDND/injections._init2</<@/home/alex/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/dragAndDrop.js:54:5
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
startDrag@resource:///org/gnome/shell/ui/dnd.js:285:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_maybeStartDrag@resource:///org/gnome/shell/ui/dnd.js:407:13
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_onEvent@resource:///org/gnome/shell/ui/dnd.js:236:24
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```

**Comment by maoschanz** [comment]
[\*alexa playing despacito in the background\*](https://i.imgur.com/LcZ1r2u.jpg)

rip shell.genericcontainer

**Comment by maoschanz** [comment]
i don't have 3.31 so I don't know if what i just did fixes the issue

**Comment by alex285** [comment]
nop it didn't! but i dont get any error logs this time. it just doesnt work

**Comment by maoschanz** [comment]
I installed GNOME Boxes just to test it with Fedora Rawhide and it works in the live session 🤔

**Comment by alex285** [comment]
hmm? it does? :/
does live session have 3.31.2? you checked?

**Comment by alex285** [comment]
I doubt, but maybe is some issue on Xorg only that I use, when live session logins you to Wayland?

**Comment by maoschanz** [comment]
i just installed the ISO, it works on both protocols, but it looks slower on Xorg (and for some reasons, when it's too slow, the drag begins when the click is released)

**Comment by alex285** [comment]
> and for some reasons, when it's too slow, the drag begins when the click is released

i can re-produce that :/

**Comment by maoschanz** [comment]
Better performance now, idk if it really fixes the issue

**Comment by alex285** [comment]
it fixes the original issue, but it crashes like crazy :/

**Comment by maoschanz** [comment]
Not on my fedora rawhide VM, what are you using nowadays ?

**Comment by maoschanz** [comment]
(it has already been published on extensions.gnome.org so i hope you're the only one with crashes 😅)
