### ISSUE TITLE
Programs Not Staying In Folders

### ISSUE THREAD

**Issue by emilward85** [Maestroschan/appfolders-manager-gnome-extension#55]
There are 6 specific applications that will not stay in a folder after I sign out of my session. When I log back in, those 6 applications are back outside of their folders. They are LibreOffice-Base, PulseAudio Volume Control, System Settings, TimeShift, Gnome Tweaks, and WoeUSB. I'm running Pop_OS! 18.04, 4.15.0-43-generic Kernel, & GNOME 3.28.3 on a Toshiba Satellite U845-S406 with an Intel i5-3317U and 8GB RAM. I have uninstalled and reinstalled the Gnome Extension as well as the .deb package and the issue persists. Is there anything I can do to make these programs stay in their folders?

**Comment by maoschanz** [comment]
Can i have the result of the command `gsettings get org.gnome.desktop.app-folders folder-children` ?

And then, for each folder, these ones:
```
gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/***/ categories
gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/***/ apps
gsettings get org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/***/ excluded-apps
```
(replace `***` with each folder id)

**Comment by Destron5683** [comment]
First comment returns:

`['Pop-Office', 'Pop-System', 'Pop-Utility', '', '_']`

All other commands return

`@as []`

**Comment by ayoungethan** [comment]
I am also running Pop!_OS 19.04 and can confirm that many changes do not persist between logins. It seems that there is some other automatic category sorting that over-rides the changes made. I am trying to disable the "use categories" function to see if that works

**Comment by ayoungethan** [comment]
gsettings get org.gnome.desktop.app-folders folder-children:
['Pop-System', 'Pop-Utility', 'Communicate', 'Write', 'Multimedia', 'Internet', 'AudioWorkstation']

**Comment by ayoungethan** [comment]
I was able to eliminate the problem by deactivating the "use categories" option in the extension, and deleting all existing app folders (including the system-generated ones) and then creating purely-manual app folders.

Not sure if any/all of those are needed, but it works for me.

**Comment by maoschanz** [comment]
>I am trying to disable the "use categories" function to see if that works

This will just hide the extension's menu entries related to categories

Pop OS is overriding things and i can't really do anything about it, I'll try in a VM this summer, but i'm quite sure the only solution is to use an other distro

**Comment by ayoungethan** [comment]
This is not true. The extension works when used as described above in my second comment: https://github.com/maoschanz/appfolders-manager-gnome-extension/issues/55#issuecomment-500574186

There is clearly some sort of conflict but it is not unresolvable. If we can understand why my workaround is effective then maybe we can create a more permanent solution. Otherwise, at least there is a workaround to keep apps organized!

**Comment by ayoungethan** [comment]
$ ls /usr/share/desktop-directories/
ActionGames.directory     Personal.directory
AdventureGames.directory  RolePlayingGames.directory
ArcadeGames.directory     Settings.directory
AudioVideo.directory      Settings-System.directory
BlocksGames.directory     SimulationGames.directory
BoardGames.directory      SportsGames.directory
CardGames.directory       StrategyGames.directory
Debian.directory          System.directory
Development.directory     System-Tools.directory
Education.directory       Utility-Accessibility.directory
Game.directory            Utility.directory
GnomeScience.directory    X-GNOME-Menu-Applications.directory
Graphics.directory        X-GNOME-Other.directory
Hardware.directory        X-GNOME-Sundry.directory
KidsGames.directory       X-GNOME-SystemSettings.directory
LogicGames.directory      X-GNOME-Utilities.directory
Network.directory         X-GNOME-WebApplications.directory
Office.directory

**Comment by maoschanz** [comment]
(nevermind, i thought it would be useful but in fact i have these files even on Debian)

**Comment by evertiro** [comment]
FYI, this isn't a bug in the extension. It's actually a bug in the 18.x series of Pop. There's a file that's autorun `/etc/xdg/autostart/pop-app-folders.desktop` on upgrades that is _supposed_ to only run on first install, but in the 18.x series the check fails and it runs every time. This is fixed in 19.x
