### ISSUE TITLE
Gnome 3.32 issues

### ISSUE THREAD

**Issue by SerdarSaglam** [Maestroschan/appfolders-manager-gnome-extension#64]
Hello
Cannot create new folder group
Cannot edit existing folder groups

Most of the Js-based add-ons are currently problematic on Gnome 3.32

**Comment by nxs-45** [comment]
App folders Management Extension is a wonderful and helpful utility. It is a utility I consider a must have. Unfortunately it no longer works on Gnome 3.32. Is there a update planned for Gnome 3.32? Thank you so much for your contribution to the esthetic and functionality of Gnome.

**Comment by maoschanz** [comment]
I'm using Debian Sid, where 3.32 doesn't even exist yet; once i'll have it the correction will need a few days to be done, so please be patient.

**Comment by nxs-45** [comment]
Thank you for your response. Your contribution to Gnome desktop is greatly
appreciated. In fact I feel your Apps folders Management extension shouild
be a part of of the Gnome desktop by default. Thank you so much for your
hard work. Just suggestion Ubuntu is based on Debian Linux, Ubuntu 19.04
Disco Dingo is currently using Gnome 3.32 http://cdimage.ubuntu.com/ under
the folder "daily-live". I hope this helps. Kind regards

**Comment by maoschanz** [comment]
I tried something, but i still don't have 3.32, so test the extension and report issues

**Comment by SerdarSaglam** [comment]
Thanks, no need to rush

Tested:
+ The folder group creation feature is running.
- The uninstall from the folder group does not work.
- The right-click menu for the folder group does not work.
? I do not remember other features

There is an automatic convert for the new GNOME js library.
She's got details here: https://github.com/hedayaty/NetSpeed/pull/89

**Comment by maoschanz** [comment]
I don't want automatic conversion because i want retro-compatibility. Right-clicking on a folder should open the same dialog as when creating a folder so the error shouldn't be dramatic, do you have logs of it ? (`journalctl -f /usr/bin/gnome-shell`)

Did you create folders/add apps/remove apps from the right-click menu or using the drag-and-drop ?

**Comment by SerdarSaglam** [comment]
Yeah, she works, but it's like a problem. It is more accurate to test when Gnome 3.32 arrives at you.
(I don't have enough English to explain the problem)
Respects

```
[serdar@fedora Masaüstü]$ journalctl -f /usr/bin/gnome-shell
-- Logs begin at Fri 2019-03-22 10:46:29 +03. --
Mar 22 13:49:15 fedora org.gnome.Shell.desktop[1133]: # _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
Mar 22 13:49:15 fedora org.gnome.Shell.desktop[1133]: # _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
Mar 22 13:49:15 fedora org.gnome.Shell.desktop[1133]: # watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
Mar 22 13:49:15 fedora org.gnome.Shell.desktop[1133]: # unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
Mar 22 13:49:15 fedora org.gnome.Shell.desktop[1133]: # watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
Mar 22 13:50:08 fedora org.gnome.Shell.desktop[1133]: # _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
Mar 22 13:50:08 fedora org.gnome.Shell.desktop[1133]: # _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
Mar 22 13:50:08 fedora org.gnome.Shell.desktop[1133]: # watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
Mar 22 13:50:08 fedora org.gnome.Shell.desktop[1133]: # unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
Mar 22 13:50:08 fedora org.gnome.Shell.desktop[1133]: # watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
Mar 22 13:51:01 fedora gnome-shell[1133]: JS ERROR: TypeError: this.close is not a function
                                          destroy@resource:///org/gnome/shell/ui/popupMenu.js:738:9
                                          destroy@resource:///org/gnome/shell/ui/popupMenu.js:878:9
                                          destroy@resource:///org/gnome/shell/ui/modalDialog.js:81:9
                                          destroy@/home/serdar/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/appfolderDialog.js:266:3
                                          _apply@/home/serdar/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/appfolderDialog.js:370:3
```

**Comment by maoschanz** [comment]
ok i understand the issue, the classes' constructor changed and i can't inject code in it like i did

- [x] fix appicon injection for dnd
- [x] fix foldericon injection for editing

**Comment by SerdarSaglam** [comment]
It works smoothly, thanks

**Comment by maoschanz** [comment]
It works smoothly... until you lock your session 😅 it's not really fixed yet

**Comment by SerdarSaglam** [comment]
I'm not logged out yet: D

**Comment by brunofjesus** [comment]
I cannot create new folders, it simply does nothing.

```
abr 15 15:15:34 oxygen gnome-shell[1492]: JS ERROR: TypeError: this._construct is not a function
                                          newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
                                          createNewFolder@/home/quark/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:295:15
                                          injectionInAppsMenus/injections._redisplay</</a<@/home/quark/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:80:6
```

I'm using ubuntu 19.04 with gnome 3.32

**Comment by maoschanz** [comment]
What version of the extension are you using ?

**Comment by brunofjesus** [comment]
> What version of the extension are you using ?

I'm using the latest version from extensions.gnome.org (v15)

**Comment by maoschanz** [comment]
The version 15 isn't supposed to be compatible with 3.32, as it's written on the extension's web page.

The code from here ("v0") still has bugs, but it is compatible with 3.32, you can use it if you really need the extension right now. And since 0 is smaller than 16 you'll be able to update the extension regularly later
