### ISSUE TITLE
Entity creation error.

### ISSUE THREAD

**Issue by 7ranceaddic7** [Maestroschan/appfolders-manager-gnome-extension#65]
Since installing, I the following error repeats itself 4-7 times in KSystemLog.

"Failed to set text from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;"

**Comment by maoschanz** [comment]
Could you please tell:

- the distribution
- the GS version
- the version of the extension (which is shown in the preferences window)

?

**Comment by 7ranceaddic7** [comment]
distribution
Ubuntu 18.10

GS version
3.30.2

extension version
v13

The extension does not function.  When I right-click on an icon in the menu (Gno-Menu) it just activates the application.  Could this be a conflict with Gno-Menu?

**Comment by maoschanz** [comment]
The 13 is quite old now, could you try to install the current one ?

The readme isn't up-to-date, you just have to download the zip, extract it, and run `install.sh`

**Comment by 7ranceaddic7** [comment]
Okay, did this.  It looks like the problem is that it's not compatible with Gno-Menu.
