### ISSUE TITLE
No able to add applicaiton to new folder

### ISSUE THREAD

**Issue by tiotrom** [Maestroschan/appfolders-manager-gnome-extension#71]
In Manjaro Gnome trying to right click - add to newappfolder does nothing. Also cannot rename folders.

**Comment by maoschanz** [comment]
Please provide:

- GNOME Shell version?
- Extension version? (written at the bottom of the preferences dialog)

**Comment by tiotrom** [comment]
Gnome Shell 3.32
V15

**Comment by maoschanz** [comment]
So this one:

![Capture d’écran de 2019-04-26 16-14-14](https://user-images.githubusercontent.com/19996113/56813944-5a138300-683e-11e9-89fc-1e4e673d4e6b.png)

**Comment by tiotrom** [comment]
A, ok, so it is not updated for the new gnome 3.32. I apologize I didn't pay attention to the versioning. Maybe Gnoem Extensions website should be more obvious about the versioning of an extension. Will you plan to update the extension soon in order to be compatible with Gnome Shell 3.32? Thank you for your work!

**Comment by maoschanz** [comment]
Yes it is planned (probably next week), but i can't be sure when it will be approved. Meanwhile you can install it from here, the remaining issues are quite minor

**Comment by tiotrom** [comment]
Thank you!
