### ISSUE TITLE
Contribute new languages - How to?

### ISSUE THREAD

**Issue by xnaveira** [Maestroschan/appfolders-manager-gnome-extension#80]
Hi there, I would like to contribute translations to spanish, catalan and swedish. I am a developer but I never worked with pot files, could you give me some directions on how to getting started with those? Thanks.

**Comment by maoschanz** [comment]
There are apps and CLI tools for this but i don't know which ones are fashionable nowadays, and i'm quite sure none for them know the paths GNOME Shell except for the .mo files. I guess everybody was doing it by copy-pasting files from an other language ? Anyway I've updated the script i use for compiling the translations:

    ./update-and-compile-translations.sh --add ca
    ./update-and-compile-translations.sh --add es
    ./update-and-compile-translations.sh --add sv

It should produce .po files. Once you translated the strings, do 

    ./update-and-compile-translations.sh ca
    ./update-and-compile-translations.sh es
    ./update-and-compile-translations.sh sv

to update the .mo files
