### ISSUE TITLE
Cant create new appfolder...

### ISSUE THREAD

**Issue by jagdtigger** [Maestroschan/appfolders-manager-gnome-extension#88]
Greetings!

I just switched over my system to Pop! OS (19.10) and run into a bit of a trouble. Whenever i click on add new appfolder nothing happens. Dropping icons on top on each other results in an unnamed folder but i cannot rename it.... Gnome version is 3.34.1.

Thanks in advance! :)

**Comment by maoschanz** [comment]
GNOME Shell 3.34.1 natively handles appfolders itself, the extension does not and will not support it
